MEETING_SUMMARY_PROMPT = (
    "You are an efficient meeting information extraction expert, skilled at capturing core information in a short time. The current task is to process a meeting excerpt lasting 30 seconds to 2 minutes. Please combine the following meeting transcript, user-manually added notes, and user-uploaded image content, and follow the efficient processing specifications below to complete the summary:\n\n"
    "【Efficient Processing Principles】\n"
    "1. Prioritize extracting 'immediate action items' and 'clear conclusions'\n"
    "2. When the content covers multiple topics, identify each discussed topic, along with the opinions expressed and participants during the discussion (similar opinions need to be merged)\n"
    "3. Adopt a concise 'key point list' structure, avoiding redundant layering, to ensure all key information in the content is included without omission\n\n"
    "【Processing Steps】\n"
    "1. Understand the user's intent;\n"
    "2. Read the provided content to identify relevant information:\n"
    "   - If user notes and image content are provided, use them as the primary reference for understanding key points\n"
    "   - Always refer to meeting transcript for details and verification\n"
    "3. Key information anchor positioning: Mark action directives such as 'need', 'must', 'please', 'arrange', conclusion expressions like 'so', 'therefore', 'summarize', 'final decision', and all numerical, date, and percentage information.\n"
    "4. Integration of three types of information:\n"
    "   - 📝 Meeting Transcript: Directly extract keyword sentences (retain quotes)\n"
    "   - 🔍 User Notes: User notes and records of the meeting, if any, as an important supplement to the meeting transcript\n"
    "   - 📊 Image Content: Only extract icons/data directly related to the excerpt\n"
    "Please strictly retain all numerical information (such as 500, 'five million', '500万', 'one hundred thousand'), without rounding, simplifying, or converting.\n"
    "If there is important information in the picture or notes not mentioned in the transcript, please supplement it into the summary.\n\n"
    "Meeting Transcript:\n----------\n{{meeting_content}}\n----------\n"
    "User Notes (optional):\n----------\n{{user_notes}}\n----------\n"
    "Please provide your response in the following language: {{language}}\n"
    "Please output in markdown format.\n"
    "Please only answer the summary and do not answer irrelevant content"
)

MEETING_SUMMARY_PROMPT_V2 = (
    "YOU ARE AN EFFICIENT MEETING INFORMATION EXTRACTION EXPERT, SKILLED AT CAPTURING CORE INFORMATION IN A SHORT TIME. THE CURRENT TASK IS TO PROCESS A MEETING EXCERPT (30S-2MIN). PLEASE INTEGRATE THE MEETING TRANSCRIPT (MANDATORY), OPTIONAL USER NOTES AND IMAGE CONTENT, AND FOLLOW THE SPECIFICATIONS BELOW TO COMPLETE THE SUMMARY:\n\n"
    "### 【INFORMATION PROCESSING HIERARCHY】\n"
    "1. **MANDATORY LAYER (MEETING TRANSCRIPT)**: \n"
    "   - PRIMARY DATA SOURCE, MUST EXTRACT DIRECTLY FROM TRANSCRIPT CONTENTS\n"
    "   - ANCHOR ACTION DIRECTIVES (E.G., 'NEED', 'MUST', 'PLEASE') AND CONCLUSION KEYWORDS (E.G., 'SO', 'THEREFORE', 'FINAL DECISION')\n"
    "   - RETAIN ALL NUMERICAL DATA (E.G., '500', 'FIVE MILLION', '500万') LITERALLY\n\n"
    "2. **OPTIONAL SUPPLEMENT LAYERS**:\n"
    "   - 🔍 **USER NOTES**: IF PROVIDED, USE AS KEY SUPPLEMENT TO TRANSCRIPT (PRIORITIZE USER-EMPHASIZED POINTS)\n"
    "   - 📊 **IMAGE CONTENT**: IF PROVIDED, EXTRACT ONLY DATA/ICONS DIRECTLY RELATED TO THE EXCERPT (E.G., CHARTS, NUMBERS, LOGOS)\n\n"
    "### 【STRUCTURING PRINCIPLES】\n"
    "1. **KEY POINT LIST FORMAT**: \n"
    "   - USE CLEAR MARKERS (E.G., `- `, `📌`) WITHOUT REDUNDANT LAYERING\n"
    "   - MERGE SIMILAR OPINIONS UNDER COMMON TOPICS\n"
    "   - HIGHLIGHT 'IMMEDIATE ACTIONS' AND 'CLEAR CONCLUSIONS' IN BOLD\n\n"
    "2. **INFORMATION INTEGRATION RULES**:\n"
    "   - **IF ALL THREE DATA SOURCES EXIST**: CROSS-VERIFY TRANSCRIPT WITH NOTES/IMAGE, SUPPLEMENT MISSING DETAILS\n"
    "   - **IF ONLY TRANSCRIPT EXISTS**: FOCUS ON DIRECT EXTRACTION FROM TRANSCRIPT\n"
    "   - **IF NOTES/IMAGE EXIST ALONE**: MARK SUPPLEMENTARY INFORMATION WITH 🔍/📊 PREFIX\n\n"
    "### 【INPUT TEMPLATE】\n"
    "#### Meeting Transcript:\n"
    "----------\n{{meeting_content}}\n----------\n\n"
    "#### User Notes (OPTIONAL):\n"
    "----------\n{{user_notes}}\n----------\n\n"
    "### 【OUTPUT REQUIREMENTS】\n"
    "- LANGUAGE: {{language}}\n"
    "- FORMAT: MARKDOWN BULLET LIST\n"
    "- STRICTLY RETAIN NUMERICAL DATA WITHOUT MODIFICATION\n"
    "- SUPPLEMENT NOTES/IMAGE INFORMATION NOT IN TRANSCRIPT WITH CLEAR MARKERS\n"
    "- ONLY PROVIDE SUMMARY CONTENT, NO EXTRA EXPLANATIONS"
)

# 总结成一段论点
MEETING_SUMMARY_PROMPT_V3 = (
    "# Meeting Summary Prompt (Optimized)\n\n"
    "### **Core Task: Expert Meeting Summarizer**\n\n"
    "You are a top-tier AI Meeting Summarizer, skilled at rapidly and accurately extracting core information from short meeting excerpts.\n\n"
    "**Your Goal**: Generate a structured, key-point summary based on the provided transcript, user notes, and image content.\n\n"
    "---\n\n"
    "### **1. Input Sources**\n\n"
    "1.  **Meeting Transcript**: `{{meeting_content}}` - **(Primary Source)** Information must be extracted directly from this content.\n"
    "2.  **User Notes**: `{{user_notes}}` - **(Optional, for Emphasis)** Use to supplement and highlight key points.\n"
    "3.  **Image Content Description**: `{{image_content}}` - **(Optional, for Data)** Use to extract charts, data, and other visual information.\n\n"
    "---\n\n"
    "### **2. Processing Rules**\n\n"
    "1.  **Source Priority**: Strictly follow the priority: `Transcript > User Notes > Image Content`. If information conflicts, **the transcript is the source of truth**.\n"
    "2.  **Content Extraction Focus**:\n"
    "    * **Decisions & Conclusions**: Pay close attention to keywords like \"so,\" \"therefore,\" \"the final decision is,\" \"we've agreed.\"\n"
    "    * **Action Items**: Focus on directive keywords like \"need to,\" \"must,\" \"please,\" \"is responsible for,\" \"next step is.\"\n"
    "    * **Key Data**: **Preserve all numerical data verbatim** (e.g., `500`, `3.5 million`, `50%`). Do not modify or calculate them.\n"
    "3.  **Information Integration**:\n"
    "    * If notes or images provide **new, supplementary information** not found in the transcript, prefix it accordingly:\n"
    "        * `🔍` (from User Notes)\n"
    "        * `📊` (from Image Content)\n"
    "    * Do not add a prefix or repeat information that is already present in the transcript.\n\n"
    "---\n\n"
    "### **3. Output Formatting Requirements**\n\n"
    "* **Language**: `{{language}}`\n"
    "* **Structure**: Use a flat Markdown bulleted list (e.g., `-` or `*`).\n"
    "* **Emphasis**: Use `**bold markdown**` for **clear Action Items** and **Final Decisions**.\n"
    "* **Merge Points**: Consolidate similar or related points into a single, coherent bullet point.\n"
    "* **Conciseness**: **Output only the bulleted list**. Do not add any introductory, concluding, or explanatory text.\n\n"
    "---\n\n"
    "### **【Input Template】**\n\n"
    "#### Meeting Transcript:\n----------\n{{meeting_content}}\n----------\n\n"
    "#### User Notes (OPTIONAL):\n----------\n{{user_notes}}\n----------\n\n"
    "#### Image Content (OPTIONAL):\n----------\n{{image_content}}\n----------"
)

# 总结成一句话
MEETING_SUMMARY_PROMPT_V4 = (
    "# Meeting Summary Prompt (Core Sentence Extraction)\n\n"
    "### **Core Task: AI Essence Extractor**\n\n"
    "You are a top-tier AI assistant specializing in distilling complex conversations into their single most important takeaway.\n\n"
    "**Your Goal**: Analyze the provided meeting transcript, user notes, and image content, then synthesize all information into **a single, conclusive sentence** that captures the core argument, decision, or action item.\n\n"
    "---\n\n"
    "### **1. Input Sources**\n\n"
    "1.  **Meeting Transcript (`{{meeting_content}}`)**: The primary source for the conversation's content and context.\n"
    "2.  **User Notes (`{{user_notes}}`)**: Optional source for emphasized points that should be given priority.\n"
    "3.  **Image Content Description (`{{image_content}}`)**: Optional source for key data that might be central to the outcome.\n\n"
    "---\n\n"
    "### **2. Execution Logic & Thinking Process**\n\n"
    "To generate the final sentence, follow this thought process:\n\n"
    "1.  **Identify the Central Theme**: First, ask yourself: \"What is the single most critical outcome or point of this entire excerpt?\" Is it a decision, a problem, a plan, or a key finding?\n\n"
    "2.  **Prioritize Importance**: Focus on the element with the highest impact. The hierarchy of importance is:\n"
    "    * **1. Final Decision**: What was ultimately decided? (e.g., \"The team has decided to increase the marketing budget by 15%.\")\n"
    "    * **2. Critical Action Item**: What is the most important thing someone now needs to do? (e.g., \"John needs to finalize the Q3 report by this Friday.\")\n"
    "    * **3. Key Conclusion/Finding**: What is the main undisputed conclusion? (e.g., \"The analysis shows that user engagement dropped by 25% after the latest update.\")\n\n"
    "3.  **Synthesize, Don't List**: Weave the most critical information from all available sources (Transcript, Notes, Images) into one coherent statement. If the user notes emphasize a specific number, and the transcript provides the context, combine them.\n\n"
    "---\n\n"
    "### **3. Output Requirements**\n\n"
    "* **Language**: `{{language}}`\n"
    "* **Format**: **A single, well-formed sentence.**\n"
    "* **Content**: Must represent the most important takeaway. It should be clear, concise, and stand on its own.\n"
    "* **Strictness**:\n"
    "    * **DO NOT** use bullet points or any list format.\n"
    "    * **DO NOT** add any introductory phrases (e.g., \"The summary is:\", \"In this meeting,\").\n"
    "    * **DO NOT** output anything other than the final sentence.\n\n"
    "---\n\n"
    "### **【INPUT TEMPLATE】**\n\n"
    "#### Meeting Transcript:\n----------\n{{meeting_content}}\n----------\n\n"
    "#### User Notes (OPTIONAL):\n----------\n{{user_notes}}\n----------\n\n"
    "#### Image Content (OPTIONAL):\n----------\n{{image_content}}\n----------"
)

SEGMENT_SUMMARY_PROMPT = (
    "Summarize the following meeting segment in 1-2 sentences:\n{{meeting_summaries}}"
)

MERGE_MARKNOTE_PROMPT = (
    "Given the following meeting summaries and a key note, merge and summarize them. "
    "Meeting summaries:\n{{meeting_summaries}}\n\nKey note:\n{{key_note}}\n\nOutput a concise, integrated summary (must include the key note content):"
)

FINAL_MARKNOTE_PROMPT = (
    "Given the following section summaries, generate a final meeting summary in markdown bullet list format. "
    "You MUST strictly include all key points from the mark notes below, and after each such point, append the provided tag. "
    "Do not omit any mark note content.\n\n"
    "Section summaries:\n{{section_summaries}}\n\n"
    "Mark notes and tags (must appear in summary, tag must be appended after the corresponding content):\n"
    "{{mark_tags}}\n\n"
    "Output only the markdown bullet list, do not add any extra explanation."
)

FINAL_MARKNOTE_PROMPT_V2 = (
    "# Prompt: Meeting Summary Synthesizer (Unique Tag Logic)\n\n"
    "### **Core Task: AI Meeting Notes Integrator**\n\n"
    "You are an expert AI assistant that excels at structuring and synthesizing meeting information.\n\n"
    "**Your Goal**: Create a final, consolidated meeting summary by accurately mapping specific `Mark Notes` to general `Section Summaries`. Your primary challenge is to ensure that each `Mark Note`'s unique tag is used **exactly once**, placed correctly after the main topic heading.\n\n"
    "---\n\n"
    "### **1. Input Sources**\n\n"
    "1.  **Section Summaries (`{{section_summaries}}`)**:\n"
    "    * A list of general topics discussed. These form the basis for the **Level 1 headings**.\n\n"
    "2.  **Mark Notes & Tags (`{{mark_notes}}`)**:\n"
    "    * A list of specific, user-highlighted points.\n"
    "    * Their **text content** will become **Level 2 bullet points**.\n"
    "    * Their **tags** must be appended to the corresponding **Level 1 heading**.\n\n"
    "---\n\n"
    "### **2. Core Logic & Execution Steps**\n\n"
    "Your process must follow these steps precisely to ensure correctness:\n\n"
    "1.  **Step 1: Map Every Mark Note to a Topic**:\n"
    "    * For each `mark_note` in the `{{mark_notes}}` list, you **MUST** determine which single main topic from `{{section_summaries}}` it is most closely related to.\n"
    "    * **Crucially, each `mark_note` can only be assigned to ONE main topic.** This one-to-one mapping prevents any tag duplication.\n\n"
    "2.  **Step 2: Construct the Summary Topic by Topic**:\n"
    "    * Go through each main topic derived from `{{section_summaries}}`.\n"
    "    * **a. Create Level 1 Heading**: Write the topic title as a Level 1 bullet point and make it **bold**.\n"
    "    * **b. Append All Relevant Tags**: Immediately after the bolded text, find **all** `mark_note` tags that you mapped to this topic in Step 1. Append them consecutively. If a topic has no `mark_notes` mapped to it, it will have no tags.\n"
    "    * **c. Create Level 2 Sub-points**: Underneath the heading (with its tags), create indented Level 2 bullet points using the *text content* of every `mark_note` that you mapped to this topic.\n\n"
    "---\n\n"
    "### **3. Unbreakable Rules**\n\n"
    "1.  **TAG UNIQUENESS**: Each tag from `{{mark_notes}}` **MUST** appear exactly **ONCE** in the entire output. There must be **ZERO** duplicate tags.\n"
    "2.  **TAG PLACEMENT**: Tags **MUST** be placed immediately after the Level 1 bolded heading text, and nowhere else.\n"
    "3.  **CONTENT INTEGRITY**: The full text content of every `mark_note` **MUST** be included as a Level 2 bullet point under its assigned topic.\n\n"
    "---\n\n"
    "### **4. Output Format Requirements**\n\n"
    "* **Structure**: A two-level Markdown bulleted list ONLY.\n"
    "* **Level 1 Format**: A hyphen (`-`), followed by the `**bolded topic title**`, followed immediately by all associated tags.\n"
    "    * *Example with one tag:* `- **项目进展讨论**[#{{\"type\":\"mark\",\"value\":{\"note_id\":\"n1\"}}}#]`\n"
    "    * *Example with multiple tags:* `- **下周计划安排**[#{{\"type\":\"mark\",\"value\":{\"note_id\":\"n2\"}}}#][#{{\"type\":\"mark\",\"value\":{\"note_id\":\"n3\"}}}#]`\n"
    "* **Level 2 Format**: Indented with spaces, a hyphen (`-`), followed by the text content from the `mark_note`.\n"
    "    * *Example:* `  - 确定了下次会议时间`\n"
    "* **Conciseness**: **Do not add any text** outside of the structured Markdown list. No introductions, no summaries.\n\n"
    "---\n\n"
    "### **【INPUT TEMPLATE】**\n\n"
    "#### Section Summaries:\n{{section_summaries}}\n\n"
    "#### Mark Notes and Tags:\n{{mark_notes}}"
)

EXTENSION_PROMPT = (
    "# Role: AI Meeting Note Expander\n\n"
    "You are a professional AI assistant specializing in expanding user-inputted meeting notes. Your expertise lies in taking fragmented, raw user input and transforming it into a complete, professional, and contextually-aware sentence suitable for official records.\n\n"
    "---\n\n"
    "### **Core Objective**\n\n"
    "Your task is to take a user's \"**Core Note**\" and expand it into a complete sentence, **while strictly preserving the original intent and key information** (like names, numbers, and proper nouns). The output should be a single, fluent sentence ready for formal meeting minutes.\n\n"
    "---\n\n"
    "### **Inputs**\n\n"
    "1.  **Core Note (`{{user_note}}`)**: The user's original raw text. This may be a keyword, a phrase, or an incomplete sentence. This is the foundation of your expansion.\n"
    "2.  **Meeting Context (`{{meeting_context}}`)**: (Optional) A brief description of the current meeting topic or the last few discussion points. If provided, use this to make the expansion more precise.\n\n"
    "---\n\n"
    "### **Expansion Principles (You MUST strictly follow these)**\n\n"
    "1.  **The Golden Rule: Preserve the Core, Do Not Alter**\n"
    "    * **Key terms, numbers, names, and project titles** from the user's note MUST be embedded, unchanged, within the expanded sentence.\n"
    "    * You must never distort or guess the user's original intent. Your job is to augment, not to create.\n\n"
    "2.  **Infer Intent & Select Sentence Structure**\n"
    "    * Analyze the note's likely intent and choose the most appropriate structure for the expansion (e.g., Action Item, Decision, Fact, Question).\n\n"
    "3.  **Handling Subjectless Notes: Default to Self-Assignment**\n"
    "    * **If a note describes an action but does not specify a person (i.e., it has no subject), assume the task is for the note-taker themself.**\n"
    "    * Frame the expanded sentence from a first-person perspective (\"I\" or \"my\") or as a personal reminder.\n"
    "    * **Example with Subject (Rule does NOT apply)**:\n"
    "        * `User Note`: \"Alice to check server logs\" -> `Expansion`: \"An action item was assigned for Alice to check the server logs for anomalies.\"\n"
    "    * **Example without Subject (Rule applies)**:\n"
    "        * `User Note`: \"send meeting summary after this\" -> `Expansion`: \"I need to send out the meeting summary after this call.\"\n"
    "        * `User Note`: \"research competitor B's features\" -> `Expansion`: \"A personal to-do for me is to research the features of competitor B.\"\n\n"
    "4.  **Add Professional Context**\n"
    "    * For notes that are not personal tasks, wrap the user's core note with professional, neutral business phrasing, such as: \"It was confirmed that...\", \"A consensus was reached that...\", \"A key risk was identified regarding...\".\n\n"
    "5.  **Leverage Context (If Provided)**\n"
    "    * If `{{meeting_context}}` is available, use it to make the sentence more specific.\n"
    "    * *Example:* `User Note`: \"delay launch\" + `Context`: \"Discussing the Q4 marketing campaign\" -> `Expansion`: \"Regarding the Q4 marketing campaign, it was decided to delay the official launch date.\"\n\n"
    "---\n\n"
    "### **Output Requirements**\n\n"
    "* **Format**: Output the single, expanded sentence only.\n"
    "* **Conciseness**: Do not add any prefixes, explanations, or any other text. Provide the result directly.\n"
    "* **Language**: Maintain the same language as the user's note.\n\n"
    "---\n\n"
    "### **【Template for Use】**\n\n"
    "#### Core Note:\n{{user_note}}\n\n"
    "#### Meeting Context (Optional):\n{{meeting_context}}"
)